### ISSUE TITLE
Despite being initialized correctly, I am still getting a null object reference error

### ISSUE THREAD

**Issue by HakimMalikOttey** [MaikuB/flutter_local_notifications#1271]
I am trying to send a test message out from my application. I have followed the readme for doing so, and I make it past the initialization stage. But when I try to show a message, I keep getting this error:

"E/MethodChannel#dexterous.com/flutter/local_notifications( 5372): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.setAction(java.lang.String)' on a null object reference"

I have looked through similar big reports, and tried changing the app icon. But even that does not resolve the issue. I have tried rolling back to a previous version of this plugin and I still get the same error. I even tried updating my SDK and nothing new. I am not sure on how to proceed with my project if this thing is not going to work. I have searched, but just never found an answer that could help me within my situation. 

What SHOULD happen is basically I would initialize the ```FlutterLocalNotificationsPlugin()``` and then push a notification that says plain title and plain body. Basically what the tutorial within the readme is telling me to do is what I am trying to achieve. 

Here is a minimum example: 
```
final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    `FlutterLocalNotificationsPlugin();
String? selectedNotificationPayload;
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  WidgetsFlutterBinding.ensureInitialized();
  runApp(app_name());
}
class app_name extends StatefulWidget {
  @override
  _app_name_state createState() => _app_name_state();
}

class app_name_state extends State<app_name>{
  @override
  void initState() {
    FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
        FlutterLocalNotificationsPlugin();
    const AndroidInitializationSettings initializationSettingsAndroid =
        AndroidInitializationSettings('@mipmap/ic_launcher');
    final IOSInitializationSettings initializationSettingsIOS =
        IOSInitializationSettings(
            onDidReceiveLocalNotification: onDidReceiveLocalNotification);
    final MacOSInitializationSettings initializationSettingsMacOS =
        MacOSInitializationSettings();
    final InitializationSettings initializationSettings =
        InitializationSettings(
            android: initializationSettingsAndroid,
            iOS: initializationSettingsIOS,
            macOS: initializationSettingsMacOS);
    WidgetsBinding.instance?.addPostFrameCallback((timeStamp) async {
      await flutterLocalNotificationsPlugin.initialize(initializationSettings,
          onSelectNotification: selectNotification);
      await _showNotification();
    });
    super.initState();
  }
Widget build(BuildContext context){
return Scaffold();

}
  Future onDidReceiveLocalNotification(
      int? id, String? title, String? body, String? payload) async {
    // display a dialog with the notification details, tap ok to go to another page
    showDialog(
      context: context,
      builder: (BuildContext context) => CupertinoAlertDialog(
        title: Text(title ?? ""),
        content: Text(body ?? ""),
        actions: [
          CupertinoDialogAction(
            isDefaultAction: true,
            child: Text('Ok'),
            onPressed: () async {
              Navigator.of(context, rootNavigator: true).pop();
            },
          )
        ],
      ),
    );
  }
Future<void> _showNotification() async {
  const AndroidNotificationDetails androidPlatformChannelSpecifics =
      AndroidNotificationDetails(
          'your channel id', 'your channel name', 'your channel description',
          importance: Importance.max,
          priority: Priority.high,
          ticker: 'ticker',
          groupKey: "key);
  const NotificationDetails platformChannelSpecifics =
      NotificationDetails(android: androidPlatformChannelSpecifics);
  await flutterLocalNotificationsPlugin.show(
    1,
    'plain title',
    'plain body',
    platformChannelSpecifics,
  );
}
}
```

My pubspec.yaml: 

```
name: appname
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_quill:
    git:
      url: https://github.com/singerdmx/flutter-quill.git
      ref: 1d22c2a
  async: ^2.4.2
  circular_menu: ^1.1.2
  # country_code_picker: ^2.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.0.1
  # email_validator: '^1.0.6'
  firebase_core: ^1.0.2
  firebase_storage: ^8.0.0
  flutter_keyboard_visibility: ^5.0.2
  font_awesome_flutter: ^8.12.0
  geocoding: ^2.0.0
  geolocator: ^7.0.1
  http: ^0.13.0
  openfoodfacts: ^1.3.2
  image_cropper: ^1.3.1
  image_picker: ^0.7.2
  drag_and_drop_gridview: ^1.0.8
  firebase_dynamic_links: ^2.0.6
  auto_size_text: ^2.1.0
  #  get_it: ^6.0.0
  #  square_in_app_payments: ^1.6.0
  intl: ^0.17.0
  lipsum: ^1.0.1
  scroll_snap_list: ^0.8.2
  #  chewie: ^1.0.0
  #  amazon_s3_cognito: ^0.5.2
  path: ^1.8.0
  #  flutter_ffmpeg: ^0.3.1
  path_provider: ^2.0.1
  permission_handler: ^6.1.1
  provider: ^4.3.3
  pull_to_refresh: ^1.6.5
  flutter_appauth: ^1.0.0+1
  table_calendar: ^3.0.1
  stripe_payment: ^1.0.6
  modal_progress_hud: ^0.1.3
  flutter_secure_storage: ^4.0.0
  flutter_webview_plugin: ^0.4.0
  webview_flutter: ^2.0.10
  workmanager: ^0.2.3
  flutter_local_notifications: ^8.0.0
  marquee: ^2.2.0
  #  keyboard_visibility: ^0.5.6
  uuid: ^2.0.0
  #  pin_code_fields: ^6.1.0
  #  video_player: ^2.0.0
  #  video_thumbnail: ^0.2.5+1
  #  export_video_frame: ^0.0.5+4
  video_compress: ^2.1.1
  #  cloud_firestore: ^1.0.2
  youtube_parser: ^1.1.0
  youtube_player_flutter: ^7.0.0+7
  country_code_picker: ^2.0.1
  email_validator: ^2.0.1
  url_launcher:
dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
  uuid: ^1.0.3
  crypto: ^3.0.0
```
AndroidManifest.xml:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="name.juicefitlife">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="juicefitlife"
        android:icon="@mipmap/ic_launcher">
        android:usesCleartextTraffic="true"
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <meta-data android:name="flutter_deeplinking_enabled" android:value="true" />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
             <intent-filter>
             <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />

            <data
                android:host="name.page.link"
                android:scheme="https" />
        </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>
    </application>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
</manifest>

```
The full error log:
```
E/MethodChannel#dexterous.com/flutter/local_notifications( 5372): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications( 5372): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.setAction(java.lang.String)' on a null object reference
E/MethodChannel#dexterous.com/flutter/local_notifications( 5372): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:166)
E/MethodChannel#dexterous.com/flutter/local_notifications( 5372): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:804)
E/MethodChannel#dexterous.com/flutter/local_notifications( 5372): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1067)
E/MethodChannel#dexterous.com/flutter/local_notifications( 5372): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:960)
E/MethodChannel#dexterous.com/flutter/local_notifications( 5372): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
```
