### ISSUE TITLE
App build failed

### ISSUE THREAD

**Issue by angel1st** [MaikuB/flutter_local_notifications#173]
Hi there,
I have just added the package to my flutter project, and build failed.
This is the output:
> FAILURE: Build failed with an exception.
> * What went wrong:
Execution failed for task ':app:processDevelopmentDebugResources'.
> Android resource linking failed
  Output:  ..\build\app\intermediates\incremental\mergeDevelopmentDebugResources\merged.dir\values\values.xml:225: error: resource android:attr/fontVariationSettings not found.
  ..\build\app\intermediates\incremental\mergeDevelopmentDebugResources\merged.dir\values\values.xml:225: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
>  Command: ..\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\ee3e40d37c3cfb66844dfd2cb1ef664d\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          E:\DevTools\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          ..\build\app\intermediates\merged_manifests\developmentDebug\processDevelopmentDebugManifest\merged\AndroidManifest.xml\
          -o\
          ..\build\app\intermediates\processed_res\developmentDebug\processDevelopmentDebugResources\out\resources-developmentDebug.ap_\
          -R\
          @..\build\app\intermediates\incremental\processDevelopmentDebugResources\resources-list-for-resources-developmentDebug.ap_.txt\
          --auto-add-overlay\
          --java\
          ..\build\app\generated\not_namespaced_r_class_sources\developmentDebug\processDevelopmentDebugResources\r\
          --custom-package\
          net.sensortronic.mmmm\
          -0\
          apk\
          --output-text-symbols\
          ..\build\app\intermediates\symbols\development\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
> * Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> BUILD FAILED in 3s
Finished with error: Gradle task assembleDevelopmentDebug failed with exit code 1

`flutter --version`
> Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (3 months ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

`pubspec.yaml`

```
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: any
  logging: ^0.11.3+2
  date_calendar: ^0.2.0
  shared_preferences: ^0.4.3
  intl: ^0.15.7
  flutter_localizations:
    sdk: flutter
  fluro: ^1.4.0
  rxdart: ^0.20.0
  sqflite: ^1.1.0
  json_serializable: ^2.0.2
  fluttertoast: ^2.2.5
  charts_flutter: ^0.5.0
  flutter_local_notifications: 0.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
```
