### ISSUE TITLE
Handling Image File Paths with Special Characters in Windows

### ISSUE THREAD

**Issue by DomingoMG** [MaikuB/flutter_local_notifications#2364]
**Describe the bug**
When I try to display a local image from my PC as a notification, if the image name contains any special characters (such as accents), the image does not show up. On the other hand, images in Flutter load correctly with or without accents. However, in the notification, it seems there is no parser to handle these cases and manage special characters.

**To Reproduce**
Set up a Flutter project with the flutter_local_notifications dependency in the specified version.
Save an image in a local path that contains special characters in its name, for example, C:\Tommy Torres - Como Tú Decías.png.
Attempt to display a notification using this image.
Notice that the image does not appear in the notification.

**Expected behavior**
The image should appear in the notification regardless of whether its name contains special characters.

**Sample code to reproduce the problem**
```dart
Future<void> showNotification() async {
  final String imagePath = 'C:\\Tommy Torres - Como Tú Decías.png'; // Change this to the path of your image
  Uri fileUri = Uri.file(imagePath);
  print('File URI: $fileUri');
  String encodedFilePath = fileUri.toFilePath(windows: Platform.isWindows);
  print('Encoded file path: $encodedFilePath');
  final imageFile = File(encodedFilePath);
  print('Image path: ${imageFile.path}');
  await _flutterLocalNotificationsPlugin.show(
    _notificationId++,
    'Test title',
    'Example body text',
    NotificationDetails(
      windows: WindowsNotificationDetails(
        audio: WindowsNotificationAudio.silent(),
        images: [
          WindowsImage.file(imageFile, altText: 'Test Image')
        ]
      ),
    ),
    payload: 'payload',
  );
}
```

**Flutter doctor output:**
```cmd
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (4 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
```

**Pubspec.yaml:**
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1

dependency_overrides: 
  flutter_local_notifications: 
    git: 
      url: https://github.com/Levi-Lesches/flutter_local_notifications.git
      ref: windows-impl
      path: flutter_local_notifications
  flutter_local_notifications_platform_interface: 
    git: 
      url: https://github.com/Levi-Lesches/flutter_local_notifications.git
      ref: windows-impl
      path: flutter_local_notifications_platform_interface
```

I will attach an image to the post to help investigate the problem. Thank you.
When downloading the photo please use this name to reproduce the error: **Tommy Torres - Como Tu Decías.png**

![Tommy Torres - Como Tu Decías](https://github.com/MaikuB/flutter_local_notifications/assets/36201422/50ead4c1-da4b-45e9-9854-55386c760853)
