### ISSUE TITLE
Monochrome Icon Problem and Compatibility Issues with Older Phones

### ISSUE THREAD

**Issue by odenath** [MaikuB/flutter_local_notifications#2528]
Hi, I'm developing an app and I'm almost finished, but I'm facing an issue with the app icon. I'm using two different packages: flutter_launcher_icons to generate icons and flutter_local_notifications to send notifications from my API.

Here are my configurations:
```
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 24 # android min sdk min:16, default 21
  adaptive_icon_monochrome: "assets/logo/monocro_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo/logo.png"
#
# dart run flutter_launcher_icons
```
This setup works fine on my Android tablet running Android 14 with UI 6.11. However, on newer phones that use monochromatic icons (when you scroll down), it only displays a black icon.

Here’s the code snippet I’m using for notification initialization:

```
    const initializationSettingsAndroid =
    AndroidInitializationSettings('@mipmap/launcher_icon');
```
Unfortunately, this doesn't work when scrolling down on recent Android versions, including Android 10.

Here’s how it looks on my tablet (working correctly):

![Image](https://github.com/user-attachments/assets/26c41bf8-d0f2-496b-8ca8-c4256c18ac1d)

And here’s how it appears on an Android 10 device (not working as expected):

![Image](https://github.com/user-attachments/assets/04d6bb31-f16f-4414-9cd4-6290d0944f6b)

This is how it’s supposed to look on modern phones: when you scroll down, the app should display a monochromatic icon. However, in my case, nothing shows up:

![Image](https://github.com/user-attachments/assets/3abcbd9f-5d51-40d0-8ceb-108e493cf805)

![Image](https://github.com/user-attachments/assets/4e442959-72c5-4b2d-817a-3134494fa61b)

I hope someone can help me figure out what’s going wrong!
